name: Deploy the blog
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to curve.space
        uses: curvenote/action-deploy@v1
        with:
          pull: true
        env:
          CURVENOTE_TOKEN: ${{ secrets.CURVENOTE_TOKEN }}
